const auroraNoireConfig = {
  id: "aurora-noire",
  slug: "aurora-noire",
  name: "Aurora Noire Monogram",
  category: "Romantic Keepsake",
  tier: "Luxury",
  price: 9,
  currency: "INR",
  description: "An ultra-luxury dark romantic digital keepsake featuring live relationship counter, candid memory gallery, flip adore notes, interactive love letter, secret truth reveal, proposal with romantic confetti, and background music.",
  coverImage: "https://images.unsplash.com/photo-1518199266791-5375a83190b7?auto=format&fit=crop&w=1600&q=80",
  features: [
    "Live Relationship & Heartbeat Counter",
    "Interactive Little Things Cards",
    "Polaroid Photo Memories with Lightbox",
    "Wax Seal Handwritten Love Letter",
    "Proposal All Over Again with Confetti Shower",
    "Custom Romantic Music / Spotify Integration"
  ],
  editableSchema: [
    { key: "partner1_name", label: "Your Name (Sender)", type: "text", defaultValue: "Kabir", placeholder: "Kabir" },
    { key: "partner2_name", label: "Partner's Name (Recipient)", type: "text", defaultValue: "Ananya", placeholder: "Ananya" },
    { key: "relationship_date", label: "Relationship / Anniversary Date (YYYY-MM-DD)", type: "text", defaultValue: "2023-11-24", placeholder: "2023-11-24" },
    { key: "occasion_badge", label: "Occasion Badge", type: "text", defaultValue: "🥂 Happy Anniversary, My Favorite Human ❤️" },
    { key: "occasion_title", label: "Keepsake Title / Subtitle", type: "text", defaultValue: "Another Year of Loving & Annoying Each Other" },
    { key: "greeting_teaser", label: "Teasing Intro Greeting", type: "textarea", defaultValue: "Can you believe we've made it another year without driving each other crazy? Happy Anniversary, my love! You're still the only person I'd willingly share my fries and blanket with (and you know that's saying a lot!). Here's to surviving each other, laughing till our stomachs hurt, and falling harder in love every single day." },
    { key: "bg_music_url", label: "Song URL (Spotify Track Link or MP3 URL)", type: "text", defaultValue: "https://open.spotify.com/track/5uUEytfFSWfTzu5EqZxQju" },
    { key: "music_title", label: "Song Title", type: "text", defaultValue: "Sab Tera" },
    { key: "music_artist", label: "Music Artist Name", type: "text", defaultValue: "Armaan Malik, Shraddha Kapoor" },
    { key: "card1Image", label: "Photo 1 (First Date)", type: "image", defaultValue: "https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=800&q=80" },
    { key: "card1Title", label: "Photo 1 Title", type: "text", defaultValue: "Our Very First Date" },
    { key: "card1Caption", label: "Photo 1 Caption", type: "text", defaultValue: "The rainy evening where two hours felt like two seconds." },
    { key: "card2Image", label: "Photo 2 (Roadtrip)", type: "image", defaultValue: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80" },
    { key: "card2Title", label: "Photo 2 Title", type: "text", defaultValue: "The First Roadtrip" },
    { key: "card2Caption", label: "Photo 2 Caption", type: "text", defaultValue: "Bad singing, wrong turns, and the most unforgettable sunset." },
    { key: "card3Image", label: "Photo 3 (Candid Moment)", type: "image", defaultValue: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=800&q=80" },
    { key: "card3Title", label: "Photo 3 Title", type: "text", defaultValue: "Goofy Afternoon" },
    { key: "card3Caption", label: "Photo 3 Caption", type: "text", defaultValue: "You trying to take a serious aesthetic picture while I couldn't stop teasing you." },
    { key: "card4Image", label: "Photo 4 (Cozy Memory)", type: "image", defaultValue: "https://images.unsplash.com/photo-1518199266791-5375a83190b7?auto=format&fit=crop&w=800&q=80" },
    { key: "card4Title", label: "Photo 4 Title", type: "text", defaultValue: "Coffee & Cozy Chaos" },
    { key: "card4Caption", label: "Photo 4 Caption", type: "text", defaultValue: "Messy hair, oversized hoodies, and pure comfort." },
    { key: "note1Title", label: "Little Thing 1 Title", type: "text", defaultValue: "Your Sleepy Morning Smile" },
    { key: "note1Content", label: "Little Thing 1 Description", type: "textarea", defaultValue: "The adorable squint you make when the alarm rings and you stubbornly pull the blanket over your head." },
    { key: "note2Title", label: "Little Thing 2 Title", type: "text", defaultValue: "That Unfiltered Laugh" },
    { key: "note2Content", label: "Little Thing 2 Description", type: "textarea", defaultValue: "The way you laugh so hard you lose your breath at silly inside jokes that nobody else understands." },
    { key: "note3Title", label: "Little Thing 3 Title", type: "text", defaultValue: "How You Reach For My Hand" },
    { key: "note3Content", label: "Little Thing 3 Description", type: "textarea", defaultValue: "The unconscious way you find my fingers whenever we're in crowded places or crossing the street." },
    { key: "note4Title", label: "Little Thing 4 Title", type: "text", defaultValue: "Our Midnight Cravings" },
    { key: "note4Content", label: "Little Thing 4 Description", type: "textarea", defaultValue: "How a random 1 AM Maggi run or ice cream drive feels like the sweetest adventure when I am with you." },
    { key: "love_letter", label: "Handwritten Love Letter", type: "textarea", defaultValue: "My love, looking back at our journey, every single day with you feels like a gift I never take for granted. Thank you for choosing me, for holding my hand when life gets messy, and for filling my world with your light and warmth. If I had to live this life a thousand times over, in every universe, I would search for you and choose you every single time. So here is me asking you all over again: Will you stay by my side, hold my hand, and be my forever love? Happy Anniversary, my heart." },
    { key: "proposal_letter_title", label: "Proposal Title", type: "text", defaultValue: "Will You Keep Choosing Me? (A Proposal All Over Again) 💍" },
    { key: "proposal_yes_title", label: "Proposal 'YES' Title", type: "text", defaultValue: "You just made me the happiest person in the universe... all over again! 💍❤️" },
    { key: "proposal_yes_message", label: "Proposal 'YES' Love Promise", type: "textarea", defaultValue: "Thank you for saying YES to me, my love. I promise to hold your hand through every high and low, make you laugh on your hardest days, and love you deeper with each passing breath. My forever was always you." }
  ],
  demoData: {
    partner1_name: "Kabir",
    partner2_name: "Ananya",
    relationship_date: "2023-11-24",
    occasion_badge: "🥂 Happy Anniversary, My Favorite Human ❤️",
    occasion_title: "Another Year of Loving & Annoying Each Other",
    greeting_teaser: "Can you believe we've made it another year without driving each other crazy? Happy Anniversary, my love! You're still the only person I'd willingly share my fries and blanket with (and you know that's saying a lot!). Here's to surviving each other, laughing till our stomachs hurt, and falling harder in love every single day.",
    bg_music_url: "https://open.spotify.com/track/5uUEytfFSWfTzu5EqZxQju",
    music_title: "Sab Tera",
    music_artist: "Armaan Malik, Shraddha Kapoor",
    card1Image: "https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=800&q=80",
    card1Title: "Our Very First Date",
    card1Caption: "The rainy evening where two hours felt like two seconds.",
    card2Image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80",
    card2Title: "The First Roadtrip",
    card2Caption: "Bad singing, wrong turns, and the most unforgettable sunset.",
    card3Image: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=800&q=80",
    card3Title: "Goofy Afternoon",
    card3Caption: "You trying to take a serious aesthetic picture while I couldn't stop teasing you.",
    card4Image: "https://images.unsplash.com/photo-1518199266791-5375a83190b7?auto=format&fit=crop&w=800&q=80",
    card4Title: "Coffee & Cozy Chaos",
    card4Caption: "Messy hair, oversized hoodies, and pure comfort.",
    note1Title: "Your Sleepy Morning Smile",
    note1Content: "The adorable squint you make when the alarm rings and you stubbornly pull the blanket over your head.",
    note2Title: "That Unfiltered Laugh",
    note2Content: "The way you laugh so hard you lose your breath at silly inside jokes that nobody else understands.",
    note3Title: "How You Reach For My Hand",
    note3Content: "The unconscious way you find my fingers whenever we're in crowded places or crossing the street.",
    note4Title: "Our Midnight Cravings",
    note4Content: "How a random 1 AM Maggi run or ice cream drive feels like the sweetest adventure when I am with you.",
    love_letter: "My love, looking back at our journey, every single day with you feels like a gift I never take for granted. Thank you for choosing me, for holding my hand when life gets messy, and for filling my world with your light and warmth. If I had to live this life a thousand times over, in every universe, I would search for you and choose you every single time. So here is me asking you all over again: Will you stay by my side, hold my hand, and be my forever love? Happy Anniversary, my heart.",
    proposal_letter_title: "Will You Keep Choosing Me? (A Proposal All Over Again) 💍",
    proposal_yes_title: "You just made me the happiest person in the universe... all over again! 💍❤️",
    proposal_yes_message: "Thank you for saying YES to me, my love. I promise to hold your hand through every high and low, make you laugh on your hardest days, and love you deeper with each passing breath. My forever was always you."
  }
};

export default auroraNoireConfig;
